name: Backend CI/CD

on:
  push:
    branches:
      - main
      - sousou
  pull_request:
    branches:
      - main
      - sousou

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn install -DskipTests
        working-directory: ./dari

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: target/*.jar

      - name: Build Docker image
        run: docker build -t soulaima54/backend:latest ./dari

      - name: Log in to Docker Hub
        run: echo "soulaima123" | docker login -u "soulaima54" --password-stdin

      - name: Push Docker image
        run: docker push soulaima54/backend:latest


